module Evergreen.Migrate.V3 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V2.Main
import Evergreen.V2.Main.Pages.Model
import Evergreen.V2.Main.Pages.Msg
import Evergreen.V2.Pages.Counter
import Evergreen.V2.Pages.Home_
import Evergreen.V2.Pages.NotFound_
import Evergreen.V2.Shared
import Evergreen.V2.Shared.Model
import Evergreen.V2.Shared.Msg
import Evergreen.V2.Types
import Evergreen.V3.Burpee
import Evergreen.V3.Main
import Evergreen.V3.Main.Pages.Model
import Evergreen.V3.Main.Pages.Msg
import Evergreen.V3.Pages.Counter
import Evergreen.V3.Pages.Home_
import Evergreen.V3.Pages.NotFound_
import Evergreen.V3.Shared
import Evergreen.V3.Shared.Model
import Evergreen.V3.Shared.Msg
import Evergreen.V3.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V2.Types.FrontendModel -> ModelMigration Evergreen.V3.Types.FrontendModel Evergreen.V3.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V2.Types.BackendModel -> ModelMigration Evergreen.V3.Types.BackendModel Evergreen.V3.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V2.Types.FrontendMsg -> MsgMigration Evergreen.V3.Types.FrontendMsg Evergreen.V3.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V2.Types.ToBackend -> MsgMigration Evergreen.V3.Types.ToBackend Evergreen.V3.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V2.Types.BackendMsg -> MsgMigration Evergreen.V3.Types.BackendMsg Evergreen.V3.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V2.Types.ToFrontend -> MsgMigration Evergreen.V3.Types.ToFrontend Evergreen.V3.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V2.Types.BackendModel -> Evergreen.V3.Types.BackendModel
migrate_Types_BackendModel old =
    { users = old.users |> Dict.map (\k -> migrate_Types_UserData)
    }


migrate_Types_FrontendModel : Evergreen.V2.Types.FrontendModel -> Evergreen.V3.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Main_Model


migrate_Types_FrontendMsg : Evergreen.V2.Types.FrontendMsg -> Evergreen.V3.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    old |> migrate_Main_Msg


migrate_Main_Model : Evergreen.V2.Main.Model -> Evergreen.V3.Main.Model
migrate_Main_Model old =
    { key = old.key
    , url = old.url
    , page = old.page |> migrate_Main_Pages_Model_Model
    , layout = old.layout
    , shared = old.shared |> migrate_Shared_Model
    }


migrate_Main_Msg : Evergreen.V2.Main.Msg -> Evergreen.V3.Main.Msg
migrate_Main_Msg old =
    case old of
        Evergreen.V2.Main.UrlRequested p0 ->
            Evergreen.V3.Main.UrlRequested p0

        Evergreen.V2.Main.UrlChanged p0 ->
            Evergreen.V3.Main.UrlChanged p0

        Evergreen.V2.Main.Page p0 ->
            Evergreen.V3.Main.Page (p0 |> migrate_Main_Pages_Msg_Msg)

        Evergreen.V2.Main.Layout p0 ->
            Evergreen.V3.Main.Layout p0

        Evergreen.V2.Main.Shared p0 ->
            Evergreen.V3.Main.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V2.Main.Batch p0 ->
            Evergreen.V3.Main.Batch (p0 |> List.map migrate_Main_Msg)


migrate_Main_Pages_Model_Model : Evergreen.V2.Main.Pages.Model.Model -> Evergreen.V3.Main.Pages.Model.Model
migrate_Main_Pages_Model_Model old =
    case old of
        Evergreen.V2.Main.Pages.Model.Home_ p0 ->
            Evergreen.V3.Main.Pages.Model.Home_ (p0 |> migrate_Pages_Home__Model)

        Evergreen.V2.Main.Pages.Model.Counter p0 ->
            Evergreen.V3.Main.Pages.Model.Counter (p0 |> migrate_Pages_Counter_Model)

        Evergreen.V2.Main.Pages.Model.NotFound_ p0 ->
            Evergreen.V3.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V2.Main.Pages.Model.Redirecting_ ->
            Evergreen.V3.Main.Pages.Model.Redirecting_

        Evergreen.V2.Main.Pages.Model.Loading_ ->
            Evergreen.V3.Main.Pages.Model.Loading_


migrate_Main_Pages_Msg_Msg : Evergreen.V2.Main.Pages.Msg.Msg -> Evergreen.V3.Main.Pages.Msg.Msg
migrate_Main_Pages_Msg_Msg old =
    case old of
        Evergreen.V2.Main.Pages.Msg.Home_ p0 ->
            Evergreen.V3.Main.Pages.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V2.Main.Pages.Msg.Counter p0 ->
            Evergreen.V3.Main.Pages.Msg.Counter (p0 |> migrate_Pages_Counter_Msg)

        Evergreen.V2.Main.Pages.Msg.NotFound_ p0 ->
            Evergreen.V3.Main.Pages.Msg.NotFound_ (p0 |> migrate_Pages_NotFound__Msg)


migrate_Pages_Counter_Model : Evergreen.V2.Pages.Counter.Model -> Evergreen.V3.Pages.Counter.Model
migrate_Pages_Counter_Model old =
    old


migrate_Pages_Counter_Msg : Evergreen.V2.Pages.Counter.Msg -> Evergreen.V3.Pages.Counter.Msg
migrate_Pages_Counter_Msg old =
    case old of
        Evergreen.V2.Pages.Counter.IncrementReps ->
            Evergreen.V3.Pages.Counter.IncrementReps

        Evergreen.V2.Pages.Counter.ResetCounter ->
            Evergreen.V3.Pages.Counter.ResetCounter


migrate_Pages_Home__Model : Evergreen.V2.Pages.Home_.Model -> Evergreen.V3.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Home__Msg : Evergreen.V2.Pages.Home_.Msg -> Evergreen.V3.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V2.Pages.Home_.IncrementReps ->
            Evergreen.V3.Pages.Home_.IncrementReps

        Evergreen.V2.Pages.Home_.ResetCounter ->
            Evergreen.V3.Pages.Home_.ResetCounter


migrate_Pages_NotFound__Model : Evergreen.V2.Pages.NotFound_.Model -> Evergreen.V3.Pages.NotFound_.Model
migrate_Pages_NotFound__Model old =
    old


migrate_Pages_NotFound__Msg : Evergreen.V2.Pages.NotFound_.Msg -> Evergreen.V3.Pages.NotFound_.Msg
migrate_Pages_NotFound__Msg old =
    case old of
        Evergreen.V2.Pages.NotFound_.NoOp ->
            Evergreen.V3.Pages.NotFound_.NoOp


migrate_Shared_Model : Evergreen.V2.Shared.Model -> Evergreen.V3.Shared.Model
migrate_Shared_Model old =
    old |> migrate_Shared_Model_Model


migrate_Shared_Model_Model : Evergreen.V2.Shared.Model.Model -> Evergreen.V3.Shared.Model.Model
migrate_Shared_Model_Model old =
    { currentBurpee = Nothing
    , currentRepGoal = 10
    , workoutHistory = []
    , initializing = False
    }


migrate_Shared_Msg : Evergreen.V2.Shared.Msg -> Evergreen.V3.Shared.Msg
migrate_Shared_Msg old =
    old |> migrate_Shared_Msg_Msg


migrate_Shared_Msg_Msg : Evergreen.V2.Shared.Msg.Msg -> Evergreen.V3.Shared.Msg.Msg
migrate_Shared_Msg_Msg old =
    case old of
        Evergreen.V2.Shared.Msg.GotNewSmashedLikes p0 ->
            Evergreen.V3.Shared.Msg.NoOp


migrate_Types_ToFrontend : Evergreen.V2.Types.ToFrontend -> Evergreen.V3.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V2.Types.LoggedIn p0 ->
            Evergreen.V3.Types.LoggedIn (p0 |> migrate_Types_UserData)


migrate_Types_UserData : Evergreen.V2.Types.UserData -> Evergreen.V3.Types.UserData
migrate_Types_UserData old =
    { currentConfig = Evergreen.V3.Burpee.default
    , dailyTarget = old.dailyTarget
    , streak = old.streak
    }
