module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V3.Burpee
import Evergreen.V3.Main
import Evergreen.V3.Main.Pages.Model
import Evergreen.V3.Main.Pages.Msg
import Evergreen.V3.Pages.Counter
import Evergreen.V3.Pages.Home_
import Evergreen.V3.Pages.NotFound_
import Evergreen.V3.Pages.PickVariant
import Evergreen.V3.Shared
import Evergreen.V3.Shared.Model
import Evergreen.V3.Shared.Msg
import Evergreen.V3.Types
import Evergreen.V3.WorkoutResult
import Evergreen.V6.Burpee
import Evergreen.V6.Main
import Evergreen.V6.Main.Pages.Model
import Evergreen.V6.Main.Pages.Msg
import Evergreen.V6.Pages.Counter
import Evergreen.V6.Pages.Home_
import Evergreen.V6.Pages.NotFound_
import Evergreen.V6.Pages.PickVariant
import Evergreen.V6.Shared
import Evergreen.V6.Shared.Model
import Evergreen.V6.Shared.Msg
import Evergreen.V6.Types
import Evergreen.V6.WorkoutResult
import Lamdera.Migrations exposing (..)
import List
import Maybe


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V3.Types.FrontendModel -> Evergreen.V6.Types.FrontendModel
migrate_Types_FrontendModel old =
    old |> migrate_Main_Model


migrate_Types_FrontendMsg : Evergreen.V3.Types.FrontendMsg -> Evergreen.V6.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    old |> migrate_Main_Msg


migrate_Burpee_Burpee : Evergreen.V3.Burpee.Burpee -> Evergreen.V6.Burpee.Burpee
migrate_Burpee_Burpee old =
    case old of
        Evergreen.V3.Burpee.Burpee p0 ->
            Evergreen.V6.Burpee.Burpee
                { name = p0.name
                , angle = p0.angle |> migrate_Burpee_GroundAngle
                , groundPart = p0.groundPart |> migrate_Burpee_GroundPart
                , topPart = p0.topPart |> migrate_Burpee_TopPart
                }


migrate_Burpee_GroundAngle : Evergreen.V3.Burpee.GroundAngle -> Evergreen.V6.Burpee.GroundAngle
migrate_Burpee_GroundAngle old =
    case old of
        Evergreen.V3.Burpee.HipInclined ->
            Evergreen.V6.Burpee.HipInclined

        Evergreen.V3.Burpee.KneeInclined ->
            Evergreen.V6.Burpee.KneeInclined

        Evergreen.V3.Burpee.LittleInclined ->
            Evergreen.V6.Burpee.LittleInclined

        Evergreen.V3.Burpee.Flat ->
            Evergreen.V6.Burpee.Flat

        Evergreen.V3.Burpee.LittleDecline ->
            Evergreen.V6.Burpee.LittleDecline

        Evergreen.V3.Burpee.KneeDecline ->
            Evergreen.V6.Burpee.KneeDecline


migrate_Burpee_GroundPart : Evergreen.V3.Burpee.GroundPart -> Evergreen.V6.Burpee.GroundPart
migrate_Burpee_GroundPart old =
    case old of
        Evergreen.V3.Burpee.Plank ->
            Evergreen.V6.Burpee.Plank

        Evergreen.V3.Burpee.MountainClimbers p0 ->
            Evergreen.V6.Burpee.MountainClimbers p0

        Evergreen.V3.Burpee.Pushups p0 ->
            Evergreen.V6.Burpee.Pushups p0

        Evergreen.V3.Burpee.NavySeals p0 ->
            Evergreen.V6.Burpee.NavySeals p0


migrate_Burpee_TopPart : Evergreen.V3.Burpee.TopPart -> Evergreen.V6.Burpee.TopPart
migrate_Burpee_TopPart old =
    case old of
        Evergreen.V3.Burpee.Jump ->
            Evergreen.V6.Burpee.Jump

        Evergreen.V3.Burpee.TuckJump ->
            Evergreen.V6.Burpee.TuckJump

        Evergreen.V3.Burpee.KneeRaise ->
            Evergreen.V6.Burpee.KneeRaise

        Evergreen.V3.Burpee.JumpingJack ->
            Evergreen.V6.Burpee.JumpingJack

        Evergreen.V3.Burpee.BoxJump ->
            Evergreen.V6.Burpee.BoxJump

        Evergreen.V3.Burpee.PullUp ->
            Evergreen.V6.Burpee.PullUp

        Evergreen.V3.Burpee.NoOp ->
            Evergreen.V6.Burpee.NoOp


migrate_Main_Model : Evergreen.V3.Main.Model -> Evergreen.V6.Main.Model
migrate_Main_Model old =
    { key = old.key
    , url = old.url
    , page = old.page |> migrate_Main_Pages_Model_Model
    , layout = old.layout
    , shared = old.shared |> migrate_Shared_Model
    }


migrate_Main_Msg : Evergreen.V3.Main.Msg -> Evergreen.V6.Main.Msg
migrate_Main_Msg old =
    case old of
        Evergreen.V3.Main.UrlRequested p0 ->
            Evergreen.V6.Main.UrlRequested p0

        Evergreen.V3.Main.UrlChanged p0 ->
            Evergreen.V6.Main.UrlChanged p0

        Evergreen.V3.Main.Page p0 ->
            Evergreen.V6.Main.Page (p0 |> migrate_Main_Pages_Msg_Msg)

        Evergreen.V3.Main.Layout p0 ->
            Evergreen.V6.Main.Layout p0

        Evergreen.V3.Main.Shared p0 ->
            Evergreen.V6.Main.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V3.Main.Batch p0 ->
            Evergreen.V6.Main.Batch (p0 |> List.map migrate_Main_Msg)


migrate_Main_Pages_Model_Model : Evergreen.V3.Main.Pages.Model.Model -> Evergreen.V6.Main.Pages.Model.Model
migrate_Main_Pages_Model_Model old =
    case old of
        Evergreen.V3.Main.Pages.Model.Home_ p0 ->
            Evergreen.V6.Main.Pages.Model.Home_ (p0 |> migrate_Pages_Home__Model)

        Evergreen.V3.Main.Pages.Model.Counter p0 ->
            Evergreen.V6.Main.Pages.Model.Counter (p0 |> migrate_Pages_Counter_Model)

        Evergreen.V3.Main.Pages.Model.PickVariant p0 ->
            Evergreen.V6.Main.Pages.Model.PickVariant (p0 |> migrate_Pages_PickVariant_Model)

        Evergreen.V3.Main.Pages.Model.NotFound_ p0 ->
            Evergreen.V6.Main.Pages.Model.NotFound_ (p0 |> migrate_Pages_NotFound__Model)

        Evergreen.V3.Main.Pages.Model.Redirecting_ ->
            Evergreen.V6.Main.Pages.Model.Redirecting_

        Evergreen.V3.Main.Pages.Model.Loading_ ->
            Evergreen.V6.Main.Pages.Model.Loading_


migrate_Main_Pages_Msg_Msg : Evergreen.V3.Main.Pages.Msg.Msg -> Evergreen.V6.Main.Pages.Msg.Msg
migrate_Main_Pages_Msg_Msg old =
    case old of
        Evergreen.V3.Main.Pages.Msg.Home_ p0 ->
            Evergreen.V6.Main.Pages.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V3.Main.Pages.Msg.Counter p0 ->
            Evergreen.V6.Main.Pages.Msg.Counter (p0 |> migrate_Pages_Counter_Msg)

        Evergreen.V3.Main.Pages.Msg.PickVariant p0 ->
            Evergreen.V6.Main.Pages.Msg.PickVariant (p0 |> migrate_Pages_PickVariant_Msg)

        Evergreen.V3.Main.Pages.Msg.NotFound_ p0 ->
            Evergreen.V6.Main.Pages.Msg.NotFound_ (p0 |> migrate_Pages_NotFound__Msg)


migrate_Pages_Counter_Model : Evergreen.V3.Pages.Counter.Model -> Evergreen.V6.Pages.Counter.Model
migrate_Pages_Counter_Model old =
    old


migrate_Pages_Counter_Msg : Evergreen.V3.Pages.Counter.Msg -> Evergreen.V6.Pages.Counter.Msg
migrate_Pages_Counter_Msg old =
    case old of
        Evergreen.V3.Pages.Counter.IncrementReps ->
            Evergreen.V6.Pages.Counter.IncrementReps

        Evergreen.V3.Pages.Counter.ResetCounter ->
            Evergreen.V6.Pages.Counter.ResetCounter

        Evergreen.V3.Pages.Counter.GotWorkoutFinishedTime p0 ->
            Evergreen.V6.Pages.Counter.GotWorkoutFinishedTime p0

        Evergreen.V3.Pages.Counter.GetWorkoutFinishedTime ->
            Evergreen.V6.Pages.Counter.GetWorkoutFinishedTime


migrate_Pages_Home__Model : Evergreen.V3.Pages.Home_.Model -> Evergreen.V6.Pages.Home_.Model
migrate_Pages_Home__Model old =
    old


migrate_Pages_Home__Msg : Evergreen.V3.Pages.Home_.Msg -> Evergreen.V6.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V3.Pages.Home_.IncrementReps ->
            Evergreen.V6.Pages.Home_.IncrementReps

        Evergreen.V3.Pages.Home_.ResetCounter ->
            Evergreen.V6.Pages.Home_.ResetCounter

        Evergreen.V3.Pages.Home_.Redirect ->
            Evergreen.V6.Pages.Home_.Redirect


migrate_Pages_NotFound__Model : Evergreen.V3.Pages.NotFound_.Model -> Evergreen.V6.Pages.NotFound_.Model
migrate_Pages_NotFound__Model old =
    old


migrate_Pages_NotFound__Msg : Evergreen.V3.Pages.NotFound_.Msg -> Evergreen.V6.Pages.NotFound_.Msg
migrate_Pages_NotFound__Msg old =
    case old of
        Evergreen.V3.Pages.NotFound_.NoOp ->
            Evergreen.V6.Pages.NotFound_.NoOp


migrate_Pages_PickVariant_Model : Evergreen.V3.Pages.PickVariant.Model -> Evergreen.V6.Pages.PickVariant.Model
migrate_Pages_PickVariant_Model old =
    { variants = old.variants |> List.map migrate_Burpee_Burpee
    }


migrate_Pages_PickVariant_Msg : Evergreen.V3.Pages.PickVariant.Msg -> Evergreen.V6.Pages.PickVariant.Msg
migrate_Pages_PickVariant_Msg old =
    case old of
        Evergreen.V3.Pages.PickVariant.PickedVariant p0 ->
            Evergreen.V6.Pages.PickVariant.PickedVariant (p0 |> migrate_Burpee_Burpee)


migrate_Shared_Model : Evergreen.V3.Shared.Model -> Evergreen.V6.Shared.Model
migrate_Shared_Model old =
    old |> migrate_Shared_Model_Model


migrate_Shared_Model_Model : Evergreen.V3.Shared.Model.Model -> Evergreen.V6.Shared.Model.Model
migrate_Shared_Model_Model old =
    { currentBurpee = old.currentBurpee |> Maybe.map migrate_Burpee_Burpee
    , currentRepGoal = old.currentRepGoal
    , workoutHistory = old.workoutHistory |> List.map migrate_Shared_Model_WorkoutResult
    , initializing = old.initializing
    }


migrate_Shared_Model_WorkoutResult : Evergreen.V3.Shared.Model.WorkoutResult -> Evergreen.V6.Shared.Model.WorkoutResult
migrate_Shared_Model_WorkoutResult old =
    { reps = old.reps
    , burpee = old.burpee |> migrate_Burpee_Burpee
    , timestamp = old.timestamp
    }


migrate_Shared_Msg : Evergreen.V3.Shared.Msg -> Evergreen.V6.Shared.Msg
migrate_Shared_Msg old =
    old |> migrate_Shared_Msg_Msg


migrate_Shared_Msg_Msg : Evergreen.V3.Shared.Msg.Msg -> Evergreen.V6.Shared.Msg.Msg
migrate_Shared_Msg_Msg old =
    case old of
        Evergreen.V3.Shared.Msg.BurpeePicked p0 ->
            Evergreen.V6.Shared.Msg.BurpeePicked (p0 |> migrate_Burpee_Burpee)

        Evergreen.V3.Shared.Msg.StoreWorkoutResult p0 ->
            Evergreen.V6.Shared.Msg.StoreWorkoutResult (p0 |> migrate_WorkoutResult_WorkoutResult)

        Evergreen.V3.Shared.Msg.GotPortMessage p0 ->
            Evergreen.V6.Shared.Msg.GotPortMessage p0

        Evergreen.V3.Shared.Msg.GotTimeForRepGoalCalculation p0 ->
            Evergreen.V6.Shared.Msg.GotTimeForRepGoalCalculation p0

        Evergreen.V3.Shared.Msg.NoOp ->
            Evergreen.V6.Shared.Msg.NoOp


migrate_WorkoutResult_WorkoutResult : Evergreen.V3.WorkoutResult.WorkoutResult -> Evergreen.V6.WorkoutResult.WorkoutResult
migrate_WorkoutResult_WorkoutResult old =
    { reps = old.reps
    , burpee = old.burpee |> migrate_Burpee_Burpee
    , timestamp = old.timestamp
    }
